### PR TITLE
Add Simplified Chinese translation.

### PR DESCRIPTION
**Pull request by willkyu**
Some translations may still require careful consideration. :P

### CODE REVIEW

**Comment by irqstorm** [comment]
Hi willkyu, thank you so much for providing this translation! There's only one minor detail I've detected, regarding:

```
<message>
         <location filename="../src/AboutWindow.cpp" line="62" />
         <source>™ and © 2020-2043 Epilogue. &lt;br&gt;All rights reserved. </source>
         <translation type="finished">and © 2020-2024 Epilogue.&lt;br&gt;版权所有。</translation>
     </message>
```

It should be 2020-2024 in the source tag, I'll correct it on the `master` branch directly.

That being said, we're preparing for v1.3.0 release the next week and we've updated quite a lot of new UI interfaces that might need translating as well. We will implement the parts you have already kindly contributed. If you're up to the challenge and have time, we would greatly appreciate your contributions in the future as well!

**Comment by willkyu** [comment]
Thanks. I'll do my best when I have some free time! 😋

**Comment by irqstorm** [comment]
> Thanks. I'll do my best when I have some free time! 😋

Great job by the way with AutoPoke!

**Comment by irqstorm** [comment]
@willkyu it's currently live on Nightly builds, do you mind if we include your Github username in the changelog when mentioning contributors?

**Comment by willkyu** [comment]
> @willkyu it's currently live on Nightly builds, do you mind if we include your Github username in the changelog when mentioning contributors?

Sure, feel free to include my Github username. Thanks for the acknowledgement! :D

**Pull request merged**
