### PR TITLE
IMPROVE German translations

### PR DESCRIPTION
**Pull request by CodebyCR**
- add missing translations
- remove `type="unfinished"` attribute for existing translations

### CODE REVIEW

**Comment by GavriloviciEduard** [comment]
I encountered issues while attempting to generate the new `.qm` file using `lrelease`. The process resulted in the following errors:
```
lrelease error: Parse error at i18n/main_de.ts:1032:48: Expected '#' or '[a-zA-Z]', but got ' '.
lrelease error: Parse error at i18n/main_de.ts:1032:67: Expected ';', but got '<'.
lrelease error: Parse error at i18n/main_de.ts:1056:14: Opening and ending tag mismatch.
```

Can you please have another look on the changes? Thanks 😄

**Comment by CodebyCR** [comment]
I'm sorry you right, @GavriloviciEduard can you try it again?
I wrote this without code highlighting, because vs code gives me a red underline for each line,
I switched to xml highlighting to get a better visual feedback this time.

**Comment by GavriloviciEduard** [comment]
lgtm. @petrutoader can you merge this please ?

**Comment by irqstorm** [comment]
@CodebyCR I really appreciate your work, thanks again for your help. Is it fine if we mention your name in the changelog for the upcoming 1.5.0 release?

Approved and merged.

**Comment by CodebyCR** [comment]
@petrutoader sure, I like the idea of ​​outsourcing some things to the community and am happy if I can support this project.

**Pull request merged**
